import type { PrintSale, PrintDateRange, PrintSummaryStats } from "../types";
export const generatePrintReport = (
  sales: PrintSale[],
  dateRange: PrintDateRange,
  summaryStats: PrintSummaryStats
): void => {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const formatCurrency = (amount: number): string =>
    new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
    }).format(amount);

  const formatDate = (dateString: string): string =>
    new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });

  const printContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Sales Report - ${new Date().toLocaleDateString()}</title>
      <style>
        body { 
          font-family: Arial, sans-serif; 
          margin: 20px; 
          color: #333;
        }
        .header { 
          text-align: center; 
          border-bottom: 2px solid #333; 
          padding-bottom: 20px; 
          margin-bottom: 30px;
        }
        .summary-cards {
          display: grid;
          grid-template-columns: repeat(5, 1fr);
          gap: 10px;
          margin-bottom: 30px;
        }
        .summary-card {
          padding: 15px;
          border: 1px solid #ddd;
          border-radius: 8px;
          text-align: center;
        }
        .summary-card h3 {
          margin: 0 0 8px 0;
          font-size: 12px;
          color: #666;
        }
        .summary-card p {
          margin: 0;
          font-size: 16px;
          font-weight: bold;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 30px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 8px;
          text-align: left;
          font-size: 12px;
        }
        th {
          background-color: #f5f5f5;
          font-weight: bold;
        }
        .footer {
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #ddd;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
        @media print {
          body { margin: 0; }
          .no-print { display: none; }
        }
        @media (max-width: 768px) {
          .summary-cards {
            grid-template-columns: repeat(2, 1fr);
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Sales Report</h1>
        <p>Period: ${formatDate(dateRange.start)} to ${formatDate(
    dateRange.end
  )}</p>
        <p>Generated on: ${new Date().toLocaleDateString()}</p>
      </div>

      <div class="summary-cards">
        <div class="summary-card">
          <h3>Total Revenue</h3>
          <p>${formatCurrency(summaryStats.totalRevenue)}</p>
        </div>
        <div class="summary-card">
          <h3>Total Profit</h3>
          <p>${formatCurrency(summaryStats.totalProfit)}</p>
        </div>
        <div class="summary-card">
          <h3>Total Sales</h3>
          <p>${summaryStats.totalSales}</p>
        </div>
        <div class="summary-card">
          <h3>Quantity Sold</h3>
          <p>${summaryStats.totalQuantity}</p>
        </div>
        <div class="summary-card">
          <h3>Avg Order Value</h3>
          <p>${formatCurrency(summaryStats.avgOrderValue)}</p>
        </div>
      </div>

      <h2>Sales Details (${sales.length} transactions)</h2>
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Product</th>
            <th>Date</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Amount</th>
            <th>Profit</th>
          </tr>
        </thead>
        <tbody>
          ${sales
            .map(
              (sale, index) => `
            <tr>
              <td>${index + 1}</td>
              <td>${sale.productName}</td>
              <td>${formatDate(sale.date || sale.createdAt)}</td>
              <td>${sale.quantity}</td>
              <td>${formatCurrency(sale.salePrice)}</td>
              <td>${formatCurrency(sale.totalAmount)}</td>
              <td>${formatCurrency(sale.profit)}</td>
            </tr>
          `
            )
            .join("")}
        </tbody>
      </table>

      <div class="footer">
        <p>Report generated by Sales Management System • ${
          sales.length
        } records</p>
      </div>

      <div class="no-print" style="margin-top: 20px; text-align: center;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #007bff; color: white; border: none; border-radius: 5px; cursor: pointer;">
          Print Report
        </button>
        <button onclick="window.close()" style="padding: 10px 20px; background: #6c757d; color: white; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;">
          Close
        </button>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(printContent);
  printWindow.document.close();
};
